apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app-pod
  template:
    metadata:
      labels:
        run: app-pod
    spec:
      containers:
      - name: myapp
        image: gideonoki/myapp:3
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: namespace2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db-pod
  template:
    metadata:
      labels:
        run: db-pod
    spec:
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
