apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /db-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: db-pv
  accessModes:
     - ReadWriteOnce

