apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app-pod
  name: app-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: app-pod
status:
  loadBalancer: {}
