
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-pod
  name: db-pod
spec:
  containers:
  - image: mongo:latest
    name: db-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-pod
  name: app-pod
spec:
  containers:
  - image: gideonoki/myapp:3
    name: app-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
